name: aperiodicMethods
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - debugpy=1.5.1=py311hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.7.0=pyha770c72_0
  - importlib_metadata=6.7.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.14.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h1ea47a8_0
  - libffi=3.4.4=hd77b12b_0
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h8bd8f75_46356
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.6=py311hf62ec03_1
  - mkl_random=1.2.2=py311hf62ec03_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy-base=1.23.5=py311h4cfcc17_1
  - openssl=3.0.8=h2bbff1b_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=py311haa95532_0
  - platformdirs=3.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py311h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.11.3=he1021f5_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pywin32=305=py311h2bbff1b_0
  - pyzmq=25.1.0=py311hd77b12b_0
  - setuptools=67.8.0=py311haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py311h2bbff1b_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py311haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.40.0
      - fooof==1.1.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - neurodsp==2.2.1
      - numpy==1.25.0
      - pandas==2.2.2
      - pillow==9.5.0
      - pyparsing==3.1.0
      - pytz==2024.1
      - scipy==1.10.1
      - seaborn==0.13.2
      - tzdata==2024.1
prefix: C:\Users\dillc\anaconda3\envs\aperiodicMethods
